### ISSUE TITLE
Task-106: Inclusión de nuevos datos en el JSON

### ISSUE THREAD

**Issue by Pabcargam** [Decide-Full-Guadalfeo/Decide-Full-Guadalfeo-Visualizacion#106]
**Descripción:** El JSON no trae consigo todos los datos necesarios, para que en el subsistema de Visualización puedan desarrollarse todas las características y mostrarse los datos relevantes.
**Fecha:** 01/01/2021
**Equipo de Desarrollo que registrar la deficiencia:** Equipo de Desarrollo de Reyes (Decide-Full-Guadalfeo-Visualización)
**Subsistema afectado por la deficiencia:** Decide-Full-Guadalfeo-Visualización
**Encargado:** -
**Como hacer que salte:** Intentando extraer los datos mencionados posteriormente del JSON, para generar gráficas y tablas estadíticas
**Cuál debería ser el resultado:** La completitud de todos los datos, en resumidas cuentas (número total de personas en el censo de dicha votación, además de su distinción entre hombres y mujeres , número de votantes finales, así como número de votantes tanto masculinos como femeninos)
**Versión navegador:** Google Chrome
**Apuntes adicionales:** Ninguno

**Comment by reyblacua** [comment]
Se cierra la tarea por repetición.
