### ISSUE TITLE
Task-135: No se ve claramente la diferencia de edad en las gráficas de barra de las medias de edad

### ISSUE THREAD

**Issue by reyblacua** [Decide-Full-Guadalfeo/Decide-Full-Guadalfeo-Visualizacion#135]
Descripción: No se ve claramente la diferencia de edad en los gráficos de barra de las medias de edad
Fecha:12/01/2021
Persona que registrar la deficiencia: Reyes Blasco Cuadrado
Como hacer que salte: Entrando en la vista de resultados de una votación y yendo a cualquier pregunta, a la gráfica de barras de la media de edad de los votantes. No se muestra claramente la diferencia de edad.
Cuál debería ser el resultado: Se debería mostrar claramente la diferencia de los valores de las gráficas.
Versión navegador: Google Chrome
Apuntes adicionales: Ninguno

**Comment by Pabcargam** [comment]
Incidencia repetida
