### ISSUE TITLE
Task-022: Porcentaje de votaciones

### ISSUE THREAD

**Issue by Pabcargam** [Decide-Full-Guadalfeo/Decide-Full-Guadalfeo-Visualizacion#22]
Mostrar en un diagráma de sectores el porcentaje de votos realizados con respecto al número de personas censadas.
Fecha: 10/12/2020

**Comment by reyblacua** [comment]
No es necesaria su implementación ya que los datos a mostrar se ven claramente en las tablas de estadísticas
